name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: $DOCKER_USER
        password: $DOCKER_PASSWORD 

    - name: Deploy to Dockerhub
      id: image
      uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kcwan18/test-app:latest
          platforms: linux/amd64
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile -t kcwan18/test-app:latest --platform=linux/amd64
    # - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v2
    # - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2
    # - name: Test
    #   run: echo ${{ steps.image.digest}}

    # - name: Update Image Version in the related HelmChart values.yaml
    #   uses: fjogeleit/yaml-update-action@main
    #   with:
    #     repository: "Kcwan18/test-helm"
    #     valueFile: 'deployment/helm/values.yaml'
    #     token: $GITHUB_TOKEN
    #     propertyPath: 'image.tag'
    #     value: ${{ steps.image.outputs.version }}
    #     message: 'Update Image Version to ${{ steps.image.outputs.version }}  