name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      -
        name: Build and push
        id: image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kcwan18/test-app:latest
          platforms: linux/amd64
      -
        name: Test
        run: echo ${{ steps.image.outputs.digest}}
  
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: Kcwan18/test-helm
          token: ${{ secrets.GITHUB_TOKEN }} 
      - 
        name: Push helm changes
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.image.outputs.digest}}
          repository: Kcwan18/test-helm
          branch: '@deploy/develop'
          targetBranch: '@deploy/develop'
          createPR: true
          message: "Update Image Digest"
          token: ${{ secrets.GH_TOKEN }}

    # - name: Update Image Version in the related HelmChart values.yaml
    #   uses: fjogeleit/yaml-update-action@main
    #   with:
    #     repository: "Kcwan18/test-helm"
    #     valueFile: 'deployment/helm/values.yaml'
    #     token: $GITHUB_TOKEN
    #     propertyPath: 'image.tag'
    #     value: ${{ steps.image.outputs.version }}
    #     message: 'Update Image Version to ${{ steps.image.outputs.version }}  